import localFont from "next/font/local";
import "./globals.css";
import StoreProvider from "@/lib/StoreProvider";
import OnlineChecker from "./OnlineChecker";

// const switzer = localFont({
//   src: "/fonts/Switzer-Black.ttf",
//   variable: "--font-switzer",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });


const switzerRegular = localFont({
  src: './fonts/Switzer-Regular.ttf',
  weight: '400', 
  style: 'normal',
  variable: '--font-switzer',
});

const switzerBold = localFont({
  src: './fonts/Switzer-Bold.ttf',
  weight: '700', 
  style: 'normal',
  variable: '--font-switzer-bold', 
});

const switzerItalic = localFont({
  src: './fonts/Switzer-Semibold.ttf',
  weight: '400',
  style: 'italic',
  variable: '--font-switzer-italic', 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${switzerRegular.variable} ${switzerBold.variable} ${switzerItalic.variable} antialiased`}
      >
        {/* <OnlineChecker /> */}
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
